freebsd_instance:
  image: freebsd-12-0-release-amd64

freebsd_task:
  name: $TOOLCHAIN x86_64-unknown-freebsd
  env:
    matrix:
      - TOOLCHAIN: stable
      - TOOLCHAIN: beta
      - TOOLCHAIN: nightly
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --default-toolchain $TOOLCHAIN
  build_script:
    - $HOME/.cargo/bin/rustup run $TOOLCHAIN cargo build --verbose
  test_script:
    - $HOME/.cargo/bin/rustup run $TOOLCHAIN cargo test --verbose
